"""Reusable UI components using Mantine."""
from app.components.curve_plot import (
    create_curve_plot,
    create_multi_panel_curve_plot,
    compute_fit_curve,
    create_overlay_plot,
)
from app.components.step_card import (
    create_step_card,
    create_step_card_skeleton,
    StepStatus,
    get_status_color,
    get_status_icon,
)
from app.components.plate_heatmap import (
    create_plate_heatmap,
    create_plate_heatmap_categorical,
    create_completion_heatmap,
    create_checkerboard_heatmap,
    create_multi_parameter_heatmap,
    create_kobs_heatmap,
    create_fmax_heatmap,
    create_rsquared_heatmap,
    well_to_coords,
)
from app.components.forest_plot import (
    create_forest_plot,
    create_snr_forest_plot,
    create_dual_forest_plot,
    create_progress_forest_plot,
    create_cross_project_forest_plot,
    get_vif_color,
    get_vif_label,
)
from app.components.violin_plot import (
    create_violin_plot,
    create_paired_violin_plot,
    create_completion_matrix,
    create_distribution_comparison,
    create_qq_plot,
    create_residual_distribution,
)
from app.components.help_panel import (
    create_help_panel,
    create_tooltip,
    create_info_icon_with_tooltip,
    create_glossary_term,
    create_help_button,
    create_quick_help,
    load_help_content,
    load_tooltips,
    load_glossary,
)
from app.components.qq_plot import (
    create_qq_plot as create_advanced_qq_plot,
    create_multi_qq_plot,
    create_residuals_vs_fitted_plot,
    create_scale_location_plot,
    generate_qq_data,
    identify_outliers,
)
from app.components.plate_grid import (
    create_plate_grid,
    create_plate_grid_skeleton,
    create_well_cell,
    create_selection_helpers,
    create_assignment_panel,
    WellState,
    get_well_state_color,
    get_well_state_style,
    well_position_to_index,
    index_to_well_position,
    get_wells_in_range,
    get_wells_in_row,
    get_wells_in_column,
    is_checkerboard_valid_well,
    validate_checkerboard_selection,
    get_checkerboard_blocked_wells,
    get_checkerboard_valid_wells,
    ROWS_96,
    COLS_96,
    ROWS_384,
    COLS_384,
    create_zoom_control,
)
# Phase 4: UX Enhancements
from app.components.comparison_drawer import (
    create_comparison_drawer,
    create_comparison_drawer_skeleton,
    create_comparison_badge,
    create_comparison_list,
    create_comparison_list_item,
    create_comparison_actions,
    get_drawer_position_styles,
    MAX_COMPARISON_ITEMS,
    DRAWER_WIDTH,
)
from app.components.construct_summary_card import (
    create_construct_summary_card,
    create_construct_summary_skeleton,
    create_construct_header,
    create_construct_metadata,
    create_statistics_panel,
    create_plate_breakdown_table,
    create_card_actions,
    format_confidence_interval,
    format_fold_change,
    get_precision_status_badge,
    PrecisionStatus,
)
from app.components.warning_suppression_ui import (
    create_warning_suppression_modal,
    create_suppressible_warning_card,
    create_suppression_reason_input,
    create_suppression_history_list,
    get_warning_type_display_name,
    get_warning_type_description,
)
from app.components.browser_check import (
    create_browser_check_banner,
    create_browser_check_store,
    create_browser_check_component,
    create_supported_browsers_list,
    get_browser_check_script,
    SUPPORTED_BROWSERS,
    MINIMUM_VERSIONS,
    BrowserSupport,
)
# Phase C: Navigation components
from app.components.navigation import (
    create_breadcrumbs,
    create_sidebar,
    create_navbar,
    create_nav_skeleton,
    PROJECT_NAV_ITEMS,
    TOP_NAV_ITEMS,
)
# Phase C: Progress tracker components
from app.components.progress_tracker import (
    create_completion_matrix as create_progress_completion_matrix,
    create_progress_bar,
    create_status_indicator,
    create_progress_summary,
    create_family_progress_table,
    create_progress_tracker_skeleton,
    COMPLETION_COLORS,
    STATUS_ICONS,
    PrecisionStatus,
    get_precision_status,
)

__all__ = [
    # Step card (Phase 1)
    "create_step_card",
    "create_step_card_skeleton",
    "StepStatus",
    "get_status_color",
    "get_status_icon",
    # Curve plot
    "create_curve_plot",
    "create_multi_panel_curve_plot",
    "compute_fit_curve",
    "create_overlay_plot",
    # Plate heatmap
    "create_plate_heatmap",
    "create_plate_heatmap_categorical",
    "create_completion_heatmap",
    "create_checkerboard_heatmap",
    "create_multi_parameter_heatmap",
    "create_kobs_heatmap",
    "create_fmax_heatmap",
    "create_rsquared_heatmap",
    "well_to_coords",
    # Forest plot
    "create_forest_plot",
    "create_snr_forest_plot",
    "create_dual_forest_plot",
    "create_progress_forest_plot",
    "create_cross_project_forest_plot",
    "get_vif_color",
    "get_vif_label",
    # Violin plot
    "create_violin_plot",
    "create_paired_violin_plot",
    "create_completion_matrix",
    "create_distribution_comparison",
    "create_qq_plot",
    "create_residual_distribution",
    # Help panel
    "create_help_panel",
    "create_tooltip",
    "create_info_icon_with_tooltip",
    "create_glossary_term",
    "create_help_button",
    "create_quick_help",
    "load_help_content",
    "load_tooltips",
    "load_glossary",
    # Q-Q plot (advanced)
    "create_advanced_qq_plot",
    "create_multi_qq_plot",
    "create_residuals_vs_fitted_plot",
    "create_scale_location_plot",
    "generate_qq_data",
    "identify_outliers",
    # Plate grid (Phase 2)
    "create_plate_grid",
    "create_plate_grid_skeleton",
    "create_well_cell",
    "create_selection_helpers",
    "create_assignment_panel",
    "WellState",
    "get_well_state_color",
    "get_well_state_style",
    "well_position_to_index",
    "index_to_well_position",
    "get_wells_in_range",
    "get_wells_in_row",
    "get_wells_in_column",
    "is_checkerboard_valid_well",
    "validate_checkerboard_selection",
    "get_checkerboard_blocked_wells",
    "get_checkerboard_valid_wells",
    "ROWS_96",
    "COLS_96",
    "ROWS_384",
    "COLS_384",
    # Comparison drawer (Phase 4)
    "create_comparison_drawer",
    "create_comparison_drawer_skeleton",
    "create_comparison_badge",
    "create_comparison_list",
    "create_comparison_list_item",
    "create_comparison_actions",
    "get_drawer_position_styles",
    "MAX_COMPARISON_ITEMS",
    "DRAWER_WIDTH",
    # Construct summary card (Phase 4)
    "create_construct_summary_card",
    "create_construct_summary_skeleton",
    "create_construct_header",
    "create_construct_metadata",
    "create_statistics_panel",
    "create_plate_breakdown_table",
    "create_card_actions",
    "format_confidence_interval",
    "format_fold_change",
    "get_precision_status_badge",
    "PrecisionStatus",
    # Warning suppression UI (Phase 4)
    "create_warning_suppression_modal",
    "create_suppressible_warning_card",
    "create_suppression_reason_input",
    "create_suppression_history_list",
    "get_warning_type_display_name",
    "get_warning_type_description",
    # Browser check (Phase 4)
    "create_browser_check_banner",
    "create_browser_check_store",
    "create_browser_check_component",
    "create_supported_browsers_list",
    "get_browser_check_script",
    "SUPPORTED_BROWSERS",
    "MINIMUM_VERSIONS",
    "BrowserSupport",
    # Navigation (Phase C)
    "create_breadcrumbs",
    "create_sidebar",
    "create_navbar",
    "create_nav_skeleton",
    "PROJECT_NAV_ITEMS",
    "TOP_NAV_ITEMS",
    # Progress tracker (Phase C)
    "create_progress_completion_matrix",
    "create_progress_bar",
    "create_status_indicator",
    "create_progress_summary",
    "create_family_progress_table",
    "create_progress_tracker_skeleton",
    "COMPLETION_COLORS",
    "STATUS_ICONS",
    "PrecisionStatus",
    "get_precision_status",
]
