"""add plasmid_size_bp to constructs

Revision ID: 09354998e331
Revises: add_exclude_from_fc
Create Date: 2026-02-06 14:27:00.885828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09354998e331'
down_revision = 'add_exclude_from_fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constructs', sa.Column('plasmid_size_bp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('constructs', 'plasmid_size_bp')
    # ### end Alembic commands ###
