"""Initial schema

Revision ID: 22ec2d6034b4
Revises: 
Create Date: 2026-02-02 23:30:36.890977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ec2d6034b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constructs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('family', sa.String(length=100), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Text(), nullable=True),
    sa.Column('is_wildtype', sa.Boolean(), nullable=True),
    sa.Column('is_unregulated', sa.Boolean(), nullable=True),
    sa.Column('mutation_description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'identifier', name='uq_construct_project_identifier')
    )
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_family_project_name')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reporter_system', sa.String(length=100), nullable=True),
    sa.Column('plate_format', sa.Enum('PLATE_96', 'PLATE_384', name='plateformat'), nullable=False),
    sa.Column('kinetic_model_type', sa.String(length=50), nullable=True),
    sa.Column('meaningful_fc_threshold', sa.Float(), nullable=True),
    sa.Column('qc_cv_threshold', sa.Float(), nullable=True),
    sa.Column('qc_outlier_threshold', sa.Float(), nullable=True),
    sa.Column('qc_drift_threshold', sa.Float(), nullable=True),
    sa.Column('qc_saturation_threshold', sa.Float(), nullable=True),
    sa.Column('qc_temperature_drift_threshold', sa.Float(), nullable=True),
    sa.Column('qc_empty_well_threshold', sa.Float(), nullable=True),
    sa.Column('qc_snr_threshold', sa.Float(), nullable=True),
    sa.Column('qc_bsi_threshold', sa.Float(), nullable=True),
    sa.Column('qc_neg_cv_threshold', sa.Float(), nullable=True),
    sa.Column('lod_coverage_factor', sa.Float(), nullable=True),
    sa.Column('loq_coverage_factor', sa.Float(), nullable=True),
    sa.Column('has_ligand_conditions', sa.Boolean(), nullable=True),
    sa.Column('ligand_name', sa.String(length=100), nullable=True),
    sa.Column('ligand_unit', sa.String(length=20), nullable=True),
    sa.Column('ligand_max_concentration', sa.Float(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('inactivity_warning_sent', sa.Boolean(), nullable=True),
    sa.Column('results_valid', sa.Boolean(), nullable=True),
    sa.Column('fitting_published', sa.Boolean(), nullable=True),
    sa.Column('fitting_published_at', sa.DateTime(), nullable=True),
    sa.Column('fitting_published_by', sa.String(length=100), nullable=True),
    sa.Column('precision_target', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('unregulated_construct_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unregulated_construct_id'], ['constructs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name_slug')
    )
    op.create_table('task_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.Enum('CURVE_FITTING', 'MCMC_SAMPLING', 'DATA_EXPORT', 'PACKAGE_VALIDATION', 'BATCH_PROCESSING', name='tasktype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('completed_steps', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_remaining_seconds', sa.Float(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_progress_project_id'), 'task_progress', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_progress_task_id'), 'task_progress', ['task_id'], unique=True)
    op.create_table('analysis_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('mcmc_chains', sa.Integer(), nullable=True),
    sa.Column('mcmc_draws', sa.Integer(), nullable=True),
    sa.Column('mcmc_tune', sa.Integer(), nullable=True),
    sa.Column('mcmc_thin', sa.Integer(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('model_comparison', sa.JSON(), nullable=True),
    sa.Column('best_model_type', sa.String(length=50), nullable=True),
    sa.Column('model_tier_metadata', sa.JSON(), nullable=True),
    sa.Column('trace_file_path', sa.String(length=500), nullable=True),
    sa.Column('trace_thin_factor', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_analysis_project_name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison_graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_construct_id', sa.Integer(), nullable=False),
    sa.Column('target_construct_id', sa.Integer(), nullable=False),
    sa.Column('path_type', sa.Enum('DIRECT', 'ONE_HOP', 'TWO_HOP', 'FOUR_HOP', name='pathtype'), nullable=False),
    sa.Column('intermediate_construct_id', sa.Integer(), nullable=True),
    sa.Column('co_occurrence_count', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intermediate_construct_id'], ['constructs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_construct_id'], ['constructs.id'], ),
    sa.ForeignKeyConstraint(['target_construct_id'], ['constructs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_construct_id', 'target_construct_id', name='uq_comparison_project_source_target')
    )
    op.create_table('experimental_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('batch_identifier', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('qc_status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='qcstatus'), nullable=False),
    sa.Column('qc_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('qc_reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('qc_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('methods_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('edited_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('plate_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('plate_format', sa.String(length=10), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('cols', sa.Integer(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('parent_template_id', sa.Integer(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_template_id'], ['plate_layouts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'version', name='uq_layout_project_name_version')
    )
    op.create_table('project_archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('archive_path', sa.String(length=500), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_by', sa.String(length=100), nullable=False),
    sa.Column('original_size_bytes', sa.Integer(), nullable=False),
    sa.Column('compressed_size_bytes', sa.Integer(), nullable=False),
    sa.Column('restored_at', sa.DateTime(), nullable=True),
    sa.Column('restored_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('current_project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hierarchical_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_version_id', sa.Integer(), nullable=False),
    sa.Column('construct_id', sa.Integer(), nullable=False),
    sa.Column('parameter_type', sa.String(length=50), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.Column('ci_lower', sa.Float(), nullable=False),
    sa.Column('ci_upper', sa.Float(), nullable=False),
    sa.Column('prob_positive', sa.Float(), nullable=True),
    sa.Column('prob_meaningful', sa.Float(), nullable=True),
    sa.Column('var_session', sa.Float(), nullable=True),
    sa.Column('var_plate', sa.Float(), nullable=True),
    sa.Column('var_residual', sa.Float(), nullable=True),
    sa.Column('n_samples', sa.Integer(), nullable=True),
    sa.Column('r_hat', sa.Float(), nullable=True),
    sa.Column('ess_bulk', sa.Float(), nullable=True),
    sa.Column('ess_tail', sa.Float(), nullable=True),
    sa.Column('posterior_samples', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcmc_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_version_id', sa.Integer(), nullable=False),
    sa.Column('draw_idx', sa.Integer(), nullable=False),
    sa.Column('chain_idx', sa.Integer(), nullable=False),
    sa.Column('total_draws', sa.Integer(), nullable=True),
    sa.Column('total_chains', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ERROR', name='checkpointstatus'), nullable=True),
    sa.Column('checkpoint_path', sa.String(length=500), nullable=False),
    sa.Column('config_path', sa.String(length=500), nullable=True),
    sa.Column('checkpoint_at', sa.DateTime(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter_correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_version_id', sa.Integer(), nullable=False),
    sa.Column('construct_id', sa.Integer(), nullable=False),
    sa.Column('parameter_1', sa.String(length=50), nullable=False),
    sa.Column('parameter_2', sa.String(length=50), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=False),
    sa.Column('ci_lower', sa.Float(), nullable=True),
    sa.Column('ci_upper', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.Integer(), nullable=False),
    sa.Column('raw_file_path', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['plate_layouts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['experimental_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precision_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('construct_id', sa.Integer(), nullable=False),
    sa.Column('analysis_version_id', sa.Integer(), nullable=False),
    sa.Column('ci_width', sa.Float(), nullable=False),
    sa.Column('comparison_type', sa.String(length=50), nullable=False),
    sa.Column('path_type', sa.String(length=50), nullable=False),
    sa.Column('plate_count', sa.Integer(), nullable=False),
    sa.Column('replicate_count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precision_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('construct_id', sa.Integer(), nullable=False),
    sa.Column('analysis_version_id', sa.Integer(), nullable=False),
    sa.Column('ci_width_actual', sa.Float(), nullable=False),
    sa.Column('ci_width_target', sa.Float(), nullable=False),
    sa.Column('is_acceptable', sa.Boolean(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('override_by', sa.String(length=100), nullable=False),
    sa.Column('override_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('construct_id', 'analysis_version_id', name='uq_override_construct_version')
    )
    op.create_table('precision_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_graph_id', sa.Integer(), nullable=False),
    sa.Column('analysis_version_id', sa.Integer(), nullable=False),
    sa.Column('variance_inflation_factor', sa.Float(), nullable=False),
    sa.Column('precision_weight', sa.Float(), nullable=False),
    sa.Column('effective_sample_size', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['comparison_graph_id'], ['comparison_graphs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('n_constructs', sa.Integer(), nullable=False),
    sa.Column('n_replicates', sa.Integer(), nullable=False),
    sa.Column('include_negative_template', sa.Boolean(), nullable=True),
    sa.Column('n_negative_template', sa.Integer(), nullable=True),
    sa.Column('include_negative_dye', sa.Boolean(), nullable=True),
    sa.Column('n_negative_dye', sa.Integer(), nullable=True),
    sa.Column('overage_percent', sa.Float(), nullable=True),
    sa.Column('dna_mass_ug', sa.Float(), nullable=True),
    sa.Column('total_reaction_volume_ul', sa.Float(), nullable=False),
    sa.Column('gtp_final_mm', sa.Float(), nullable=True),
    sa.Column('gtp_stock_mm', sa.Float(), nullable=True),
    sa.Column('atp_final_mm', sa.Float(), nullable=True),
    sa.Column('atp_stock_mm', sa.Float(), nullable=True),
    sa.Column('ctp_final_mm', sa.Float(), nullable=True),
    sa.Column('ctp_stock_mm', sa.Float(), nullable=True),
    sa.Column('utp_final_mm', sa.Float(), nullable=True),
    sa.Column('utp_stock_mm', sa.Float(), nullable=True),
    sa.Column('dfhbi_final_um', sa.Float(), nullable=True),
    sa.Column('dfhbi_stock_um', sa.Float(), nullable=True),
    sa.Column('master_mix_volumes', sa.JSON(), nullable=True),
    sa.Column('total_master_mix_volume_ul', sa.Float(), nullable=True),
    sa.Column('protocol_text', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['experimental_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('well_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('well_position', sa.String(length=10), nullable=False),
    sa.Column('construct_id', sa.Integer(), nullable=True),
    sa.Column('well_type', sa.Enum('EMPTY', 'SAMPLE', 'BLANK', 'NEGATIVE_CONTROL_NO_TEMPLATE', 'NEGATIVE_CONTROL_NO_DYE', name='welltype'), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('paired_with_id', sa.Integer(), nullable=True),
    sa.Column('replicate_group', sa.String(length=50), nullable=True),
    sa.Column('ligand_concentration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['layout_id'], ['plate_layouts.id'], ),
    sa.ForeignKeyConstraint(['paired_with_id'], ['well_assignments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layout_id', 'well_position', name='uq_assignment_layout_position')
    )
    op.create_table('background_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.Column('timepoint', sa.Float(), nullable=False),
    sa.Column('mean_background', sa.Float(), nullable=False),
    sa.Column('sd_background', sa.Float(), nullable=False),
    sa.Column('n_controls', sa.Integer(), nullable=False),
    sa.Column('polynomial_coefficients', sa.JSON(), nullable=True),
    sa.Column('correction_method', sa.Enum('SIMPLE', 'TIME_DEPENDENT', 'SPATIAL', name='correctionmethod'), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plate_id'], ['plates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction_dna_additions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reaction_setup_id', sa.Integer(), nullable=False),
    sa.Column('construct_id', sa.Integer(), nullable=True),
    sa.Column('construct_name', sa.String(length=100), nullable=False),
    sa.Column('is_negative_control', sa.Boolean(), nullable=True),
    sa.Column('negative_control_type', sa.String(length=50), nullable=True),
    sa.Column('dna_stock_concentration_ng_ul', sa.Float(), nullable=True),
    sa.Column('dna_volume_ul', sa.Float(), nullable=False),
    sa.Column('water_adjustment_ul', sa.Float(), nullable=False),
    sa.Column('total_addition_ul', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ),
    sa.ForeignKeyConstraint(['reaction_setup_id'], ['reaction_setups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.Column('construct_id', sa.Integer(), nullable=False),
    sa.Column('replicate_number', sa.Integer(), nullable=False),
    sa.Column('total_volume_ul', sa.Float(), nullable=False),
    sa.Column('wells_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ),
    sa.ForeignKeyConstraint(['plate_id'], ['plates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARSING', 'PARSED', 'PARSE_FAILED', 'VALIDATING', 'VALIDATED', 'VALIDATION_FAILED', 'PROCESSING', 'PROCESSED', 'PROCESS_FAILED', 'EXPIRED', name='uploadstatus'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('parsed_metadata', sa.JSON(), nullable=True),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('plate_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['plate_layouts.id'], ),
    sa.ForeignKeyConstraint(['plate_id'], ['plates.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['experimental_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_project_id'), 'uploads', ['project_id'], unique=False)
    op.create_index(op.f('ix_uploads_status'), 'uploads', ['status'], unique=False)
    op.create_index(op.f('ix_uploads_upload_id'), 'uploads', ['upload_id'], unique=True)
    op.create_table('wells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.Column('reaction_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('construct_id', sa.Integer(), nullable=True),
    sa.Column('well_type', sa.Enum('EMPTY', 'SAMPLE', 'BLANK', 'NEGATIVE_CONTROL_NO_TEMPLATE', 'NEGATIVE_CONTROL_NO_DYE', name='welltype'), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('paired_with_id', sa.Integer(), nullable=True),
    sa.Column('volume_ul', sa.Float(), nullable=True),
    sa.Column('split_index', sa.Integer(), nullable=True),
    sa.Column('ligand_concentration', sa.Float(), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=True),
    sa.Column('exclusion_reason', sa.String(length=500), nullable=True),
    sa.Column('fit_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'NEEDS_REVIEW', name='fitstatus'), nullable=True),
    sa.Column('is_checkerboard_valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['construct_id'], ['constructs.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['paired_with_id'], ['wells.id'], ),
    sa.ForeignKeyConstraint(['plate_id'], ['plates.id'], ),
    sa.ForeignKeyConstraint(['reaction_id'], ['reactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_id', 'position', name='uq_well_plate_position')
    )
    op.create_table('fit_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('f_baseline', sa.Float(), nullable=True),
    sa.Column('f_baseline_se', sa.Float(), nullable=True),
    sa.Column('f_max', sa.Float(), nullable=True),
    sa.Column('f_max_se', sa.Float(), nullable=True),
    sa.Column('k_obs', sa.Float(), nullable=True),
    sa.Column('k_obs_se', sa.Float(), nullable=True),
    sa.Column('t_lag', sa.Float(), nullable=True),
    sa.Column('t_lag_se', sa.Float(), nullable=True),
    sa.Column('r_squared', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('aic', sa.Float(), nullable=True),
    sa.Column('converged', sa.Boolean(), nullable=True),
    sa.Column('residual_normality_pvalue', sa.Float(), nullable=True),
    sa.Column('fitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('well_id')
    )
    op.create_table('fold_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_well_id', sa.Integer(), nullable=False),
    sa.Column('control_well_id', sa.Integer(), nullable=False),
    sa.Column('fc_fmax', sa.Float(), nullable=True),
    sa.Column('fc_fmax_se', sa.Float(), nullable=True),
    sa.Column('fc_kobs', sa.Float(), nullable=True),
    sa.Column('fc_kobs_se', sa.Float(), nullable=True),
    sa.Column('delta_tlag', sa.Float(), nullable=True),
    sa.Column('delta_tlag_se', sa.Float(), nullable=True),
    sa.Column('log_fc_fmax', sa.Float(), nullable=True),
    sa.Column('log_fc_fmax_se', sa.Float(), nullable=True),
    sa.Column('log_fc_kobs', sa.Float(), nullable=True),
    sa.Column('log_fc_kobs_se', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['control_well_id'], ['wells.id'], ),
    sa.ForeignKeyConstraint(['test_well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_well_id', 'control_well_id', name='uq_foldchange_test_control')
    )
    op.create_table('raw_data_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('timepoint', sa.Float(), nullable=False),
    sa.Column('fluorescence_raw', sa.Float(), nullable=False),
    sa.Column('fluorescence_corrected', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warning_suppressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('warning_type', sa.Enum('INCOMPLETE_PLATE', 'TEMPERATURE_DEVIATION', 'MISSING_NEGATIVE_CONTROL', 'LOW_REPLICATE_COUNT', 'HIGH_CV', 'OUTLIER_DETECTED', 'EDGE_EFFECT', 'MISSING_WELLS', name='warningtype'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('suppressed_by', sa.String(length=255), nullable=False),
    sa.Column('suppressed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plate_id'], ['plates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warning_suppressions_plate_id'), 'warning_suppressions', ['plate_id'], unique=False)
    op.create_index(op.f('ix_warning_suppressions_well_id'), 'warning_suppressions', ['well_id'], unique=False)
    op.create_table('fit_result_archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('superseding_fit_id', sa.Integer(), nullable=True),
    sa.Column('original_fit_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('f_baseline', sa.Float(), nullable=True),
    sa.Column('f_baseline_se', sa.Float(), nullable=True),
    sa.Column('f_max', sa.Float(), nullable=True),
    sa.Column('f_max_se', sa.Float(), nullable=True),
    sa.Column('k_obs', sa.Float(), nullable=True),
    sa.Column('k_obs_se', sa.Float(), nullable=True),
    sa.Column('t_lag', sa.Float(), nullable=True),
    sa.Column('t_lag_se', sa.Float(), nullable=True),
    sa.Column('r_squared', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('aic', sa.Float(), nullable=True),
    sa.Column('converged', sa.Boolean(), nullable=True),
    sa.Column('residual_normality_pvalue', sa.Float(), nullable=True),
    sa.Column('original_fitted_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_by', sa.String(length=100), nullable=True),
    sa.Column('superseded_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['superseding_fit_id'], ['fit_results.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fit_result_archives_well_id'), 'fit_result_archives', ['well_id'], unique=False)
    op.create_table('signal_quality_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fit_result_id', sa.Integer(), nullable=False),
    sa.Column('snr', sa.Float(), nullable=True),
    sa.Column('sbr', sa.Float(), nullable=True),
    sa.Column('above_lod', sa.Boolean(), nullable=True),
    sa.Column('above_loq', sa.Boolean(), nullable=True),
    sa.Column('lod_value', sa.Float(), nullable=True),
    sa.Column('loq_value', sa.Float(), nullable=True),
    sa.Column('min_detectable_fc', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fit_result_id'], ['fit_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fit_result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_quality_metrics')
    op.drop_index(op.f('ix_fit_result_archives_well_id'), table_name='fit_result_archives')
    op.drop_table('fit_result_archives')
    op.drop_index(op.f('ix_warning_suppressions_well_id'), table_name='warning_suppressions')
    op.drop_index(op.f('ix_warning_suppressions_plate_id'), table_name='warning_suppressions')
    op.drop_table('warning_suppressions')
    op.drop_table('raw_data_points')
    op.drop_table('fold_changes')
    op.drop_table('fit_results')
    op.drop_table('wells')
    op.drop_index(op.f('ix_uploads_upload_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_status'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_project_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_table('reactions')
    op.drop_table('reaction_dna_additions')
    op.drop_table('background_estimates')
    op.drop_table('well_assignments')
    op.drop_table('reaction_setups')
    op.drop_table('precision_weights')
    op.drop_table('precision_overrides')
    op.drop_table('precision_histories')
    op.drop_table('plates')
    op.drop_table('parameter_correlations')
    op.drop_table('mcmc_checkpoints')
    op.drop_table('hierarchical_results')
    op.drop_table('user_sessions')
    op.drop_table('project_archives')
    op.drop_table('plate_layouts')
    op.drop_table('methods_texts')
    op.drop_table('experimental_sessions')
    op.drop_table('comparison_graphs')
    op.drop_table('audit_logs')
    op.drop_table('analysis_versions')
    op.drop_index(op.f('ix_task_progress_task_id'), table_name='task_progress')
    op.drop_index(op.f('ix_task_progress_project_id'), table_name='task_progress')
    op.drop_table('task_progress')
    op.drop_table('projects')
    op.drop_table('families')
    op.drop_table('constructs')
    # ### end Alembic commands ###
