"""Add ligand_condition to WellAssignment, Well, FoldChange, HierarchicalResult

Revision ID: 81915dfa5605
Revises: 09354998e331
Create Date: 2026-02-06 23:19:27.992295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81915dfa5605'
down_revision = '09354998e331'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fold_changes', sa.Column('ligand_condition', sa.String(length=10), nullable=True))
    op.add_column('fold_changes', sa.Column('comparison_type', sa.String(length=30), nullable=True))
    op.add_column('hierarchical_results', sa.Column('ligand_condition', sa.String(length=10), nullable=True))
    op.add_column('well_assignments', sa.Column('ligand_condition', sa.String(length=10), nullable=True))
    op.add_column('wells', sa.Column('ligand_condition', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wells', 'ligand_condition')
    op.drop_column('well_assignments', 'ligand_condition')
    op.drop_column('hierarchical_results', 'ligand_condition')
    op.drop_column('fold_changes', 'comparison_type')
    op.drop_column('fold_changes', 'ligand_condition')
    # ### end Alembic commands ###
